name: GHActions CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on:
      - ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with: # keep in sync with package.json
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - name: Check Typescript
        run: |
          pnpm typecheck
      - name: Check Prettier
        run: |
          pnpm prettier
      - name: Run Tests
        run: |
          npm i -g pnpm && pnpm lint && pnpm test:ci
