name: Pre-Release

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to create new pre-release tag for'
        required: true
        type: string

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pre-release:
    name: Pre-Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with: # keep in sync with package.json
          version: 8

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm ci:prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
